server:
   port: 8010
   
   
   
spring:
  application:
    name: Doctors-Page
    
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8061/eureka/
  instance:
    hostname: localhost